/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FUNCIONESBANCO_H_RPCGEN
#define _FUNCIONESBANCO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct depositar_retirar {
	int eleccion;
	int valor;
	int saldo;
};
typedef struct depositar_retirar depositar_retirar;

#define SERVIDOR_BANCARIO 0x20000001
#define VERSION_ACTUALIZAR 1

#if defined(__STDC__) || defined(__cplusplus)
#define actualizar 1
extern  int * actualizar_1(depositar_retirar *, CLIENT *);
extern  int * actualizar_1_svc(depositar_retirar *, struct svc_req *);
extern int servidor_bancario_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define actualizar 1
extern  int * actualizar_1();
extern  int * actualizar_1_svc();
extern int servidor_bancario_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_depositar_retirar (XDR *, depositar_retirar*);

#else /* K&R C */
extern bool_t xdr_depositar_retirar ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FUNCIONESBANCO_H_RPCGEN */
