/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "FuncionesBanco.h"

void
servidor_bancario_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	depositar_retirar  actualizar_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SERVIDOR_BANCARIO, VERSION_ACTUALIZAR, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	printf("\n++++++++ BANCO AREVALO +++++++\n");
	int eleccion;
	int valor;

	printf("Ingrese un valor 1 para Despositar\n");
	printf("Ingrese un valor 2 para Retirar\n");
	scanf("%d", &eleccion);

	printf("Ingresar cantidad de dinero\n");
	scanf("%d", &valor);

	actualizar_1_arg.eleccion = eleccion;
	actualizar_1_arg.valor = valor;
	actualizar_1_arg.saldo = 0;
	result_1 = actualizar_1(&actualizar_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		printf("Usted depositó $%d en la cuenta\n", valor);
		printf("Tiene actualmente: $%d ", *result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	servidor_bancario_1 (host);
exit (0);
}
